/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao.areaFarmacia;

import controle.areaFarmacia.VisaoPedidoControle;
import java.util.List;
import modelo.ItemPedido;
import modelo.Pedido;

/**
 *
 * @author Mateus
 */
public class VisaoPedido extends javax.swing.JFrame {

    /**
     * Creates new form VisaoPedido
     */
    public VisaoPedido() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public VisaoPedido(Pedido pedido, javax.swing.JFrame pai) {
        this.pedido = pedido;
        this.pai = pai;
        initComponents();
        carregar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableItensPedido = new javax.swing.JTable();
        jButtonAceitar = new javax.swing.JButton();
        jButtonRecusar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelNome = new javax.swing.JLabel();
        jLabelTelefone = new javax.swing.JLabel();
        jLabelEndereco = new javax.swing.JLabel();
        jLabelHora = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Pedido");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jTableItensPedido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicamento", "Quantidade", "Preço Unitário"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTableItensPedido);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 196, 440, 210));

        jButtonAceitar.setText("Aceitar");
        jButtonAceitar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonAceitarMouseClicked(evt);
            }
        });
        jButtonAceitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAceitarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAceitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, -1, -1));

        jButtonRecusar.setText("Recusar");
        jButtonRecusar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRecusarMouseClicked(evt);
            }
        });
        getContentPane().add(jButtonRecusar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 420, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalhes "));

        jLabel2.setText("Cliente:");

        jLabel3.setText("Telefone:");

        jLabel4.setText("Endereço:");

        jLabel5.setText("Hora do pedido:");

        jLabelNome.setText("nome");

        jLabelTelefone.setText("telefone");

        jLabelEndereco.setText("endereço");

        jLabelHora.setText("Hora");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNome)
                    .addComponent(jLabelTelefone)
                    .addComponent(jLabelEndereco)
                    .addComponent(jLabelHora))
                .addContainerGap(276, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabelNome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelTelefone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabelEndereco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabelHora))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 430, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAceitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAceitarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAceitarActionPerformed

    private void jButtonAceitarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAceitarMouseClicked
        ConsultarPedidosFarmacia consultarPedidos = new ConsultarPedidosFarmacia();
        // Codigo para atualizar a tabela
        consultarPedidos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonAceitarMouseClicked

    private void jButtonRecusarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRecusarMouseClicked
        ConsultarPedidosFarmacia consultarPedidos = new ConsultarPedidosFarmacia();
        // Codigo para atualizar a tabela
        consultarPedidos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonRecusarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisaoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisaoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisaoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisaoPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisaoPedido().setVisible(true);
            }
        });
    }

    public void carregar()
    {
        List<ItemPedido> itensPedido = new VisaoPedidoControle().listarItensPedido(pedido.getIdPedido());
        javax.swing.table.DefaultTableModel dtm = (javax.swing.table.DefaultTableModel)jTableItensPedido.getModel();
        for (ItemPedido itemPedido : itensPedido)
        {
            dtm.addRow(new Object[]{itemPedido.getMedicamento().getNome(), itemPedido.getQuantidade(), itemPedido.getPrecoUnitario()});
        }
        jLabelNome.setText(pedido.getCliente().getNome());
        jLabelTelefone.setText(pedido.getCliente().getTelefone());
        jLabelEndereco.setText(pedido.getCliente().getEndereco());
        jLabelHora.setText(pedido.getData().toString());
    }
    
    Pedido pedido;
    javax.swing.JFrame pai;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAceitar;
    private javax.swing.JButton jButtonRecusar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelEndereco;
    private javax.swing.JLabel jLabelHora;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableItensPedido;
    // End of variables declaration//GEN-END:variables
}
